stages:
  - test

variables:
  SRCDIR: /go/src/github.com/go-kivik/couchdb
  GO111MODULE: "on"

.test: &test_template
  stage: test
  services:
    - name: couchdb:2.2.0
      alias: couch22
    - name: apache/couchdb:2.3.1
      alias: couch23
    - name: couchdb:3.0.1
      alias: couch30
    - name: couchdb:3.1.2
      alias: couch31
  variables:
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: abc123
    KIVIK_TEST_DSN_COUCH22: http://admin:abc123@couch22:5984/
    KIVIK_TEST_DSN_COUCH23: http://admin:abc123@couch23:5984/
    KIVIK_TEST_DSN_COUCH30: http://admin:abc123@couch30:5984/
    KIVIK_TEST_DSN_COUCH31: http://admin:abc123@couch31:5984/
  before_script:
    - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH22}
    - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH23}
    - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH30}
    - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH31}
  script:
    - go mod download
    - ./script/test_version.sh
    - go test -race -tags=livetest ./...

.nomod: &nomod_template
  <<: *test_template
  script:
    - mkdir -p /go/src
    - ln -s /builds /go/src/github.com
    - cd ${SRCDIR}
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - dep ensure && dep status
    - ./script/test_version.sh
    - go test -race -tags=livetest ./...

linter:
  stage: test
  image: golangci/golangci-lint:v1.52.2
  script:
    - go mod download
    - golangci-lint run ./...
    - ./script/check-license.sh
    - go mod tidy -compat=1.17 && git diff --exit-code

coverage:
  stage: test
  image: golang:1.20
  services: []
  before_script:
    - ""
  script:
    - go mod download
    - ./script/coverage.sh

go-1.17:
  <<: *test_template
  image: golang:1.17

go-1.18:
  <<: *test_template
  image: golang:1.18

go-1.19:
  <<: *test_template
  image: golang:1.19

go-1.20:
  <<: *test_template
  image: golang:1.20

go-rc:
  <<: *test_template
  image: golang:rc
  allow_failure: true
